// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqa-JVntWI8S_BUgMm3U49WgXIAu25C58',
    appId: '1:441603165560:web:da22368732200111be8c8d',
    messagingSenderId: '441603165560',
    projectId: 'ezbill123',
    authDomain: 'ezbill123.firebaseapp.com',
    databaseURL: 'https://ezbill123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezbill123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfArEhKf2I1xX43D4wBU51wuOgbv01kvk',
    appId: '1:441603165560:android:66d9fa987e211be8be8c8d',
    messagingSenderId: '441603165560',
    projectId: 'ezbill123',
    databaseURL: 'https://ezbill123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezbill123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVUYNPHGESzojKynRVgMUYf6BFYWXorAU',
    appId: '1:441603165560:ios:e983f82fb60bb76fbe8c8d',
    messagingSenderId: '441603165560',
    projectId: 'ezbill123',
    databaseURL: 'https://ezbill123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezbill123.appspot.com',
    iosBundleId: 'com.example.ezbill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVUYNPHGESzojKynRVgMUYf6BFYWXorAU',
    appId: '1:441603165560:ios:e983f82fb60bb76fbe8c8d',
    messagingSenderId: '441603165560',
    projectId: 'ezbill123',
    databaseURL: 'https://ezbill123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezbill123.appspot.com',
    iosBundleId: 'com.example.ezbill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqa-JVntWI8S_BUgMm3U49WgXIAu25C58',
    appId: '1:441603165560:web:20ca7ad2aa6eda4bbe8c8d',
    messagingSenderId: '441603165560',
    projectId: 'ezbill123',
    authDomain: 'ezbill123.firebaseapp.com',
    databaseURL: 'https://ezbill123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezbill123.appspot.com',
  );
}
